{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ef6358ca-25b4-4d43-8d20-61a3a84e59d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\srv_resolver.py\", line 72, in _resolve_uri\n",
      "    results = resolver.query('_mongodb._tcp.' + self.__fqdn, 'SRV',\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\dns\\resolver.py\", line 1597, in query\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\dns\\resolver.py\", line 1564, in resolve\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\dns\\resolver.py\", line 1320, in resolve\n",
      "    canonical = tuples[0][3]\n",
      "                          ^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\dns\\resolver.py\", line 1076, in _compute_timeout\n",
      "dns.resolver.LifetimeTimeout: The resolution lifetime expired after 21.604 seconds: Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Local\\Temp\\ipykernel_17000\\936044167.py\", line 9, in <module>\n",
      "    client = MongoClient(\"mongodb+srv://crptointel:capstone@cluster0.00owi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0\")\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\mongo_client.py\", line 639, in __init__\n",
      "    res = uri_parser.parse_uri(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\uri_parser.py\", line 500, in parse_uri\n",
      "    nodes = dns_resolver.get_hosts()\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\srv_resolver.py\", line 102, in get_hosts\n",
      "    _, nodes = self._get_srv_response_and_hosts(True)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\srv_resolver.py\", line 83, in _get_srv_response_and_hosts\n",
      "    results = self._resolve_uri(encapsulate_errors)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\pymongo\\srv_resolver.py\", line 79, in _resolve_uri\n",
      "    raise ConfigurationError(str(exc))\n",
      "pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.604 seconds: Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.; Server Do53:64.71.255.204@53 answered The DNS operation timed out.; Server Do53:64.71.255.198@53 answered The DNS operation timed out.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 2120, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 1326, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 1088, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 970, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "    ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\ultratb.py\", line 792, in lines\n",
      "    return self._sd.lines\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\core.py\", line 734, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\core.py\", line 681, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\stack_data\\core.py\", line 660, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"C:\\Users\\Akshay7798\\AppData\\Roaming\\Python\\Python311\\site-packages\\executing\\executing.py\", line 116, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "#kafka_consumer\n",
    "\n",
    "from kafka import KafkaConsumer\n",
    "import json\n",
    "from pymongo import MongoClient\n",
    "\n",
    "# Connect to MongoDB Atlas\n",
    "\n",
    "client = MongoClient(\"mongodb+srv://crptointel:capstone@cluster0.00owi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0\")\n",
    "\n",
    "db = client.crypto_data\n",
    "collection = db.kraken_prices\n",
    "\n",
    "# Kafka Consumer Setup\n",
    "consumer = KafkaConsumer(\n",
    "    'kraken_prices',\n",
    "    bootstrap_servers='localhost:9092',\n",
    "    value_deserializer=lambda x: json.loads(x.decode('utf-8'))\n",
    ")\n",
    "\n",
    "print(\"Consumer started...\")\n",
    "for message in consumer:\n",
    "    price_data = message.value\n",
    "    print(f\"Received: {price_data}\")\n",
    "\n",
    "    # Store in MongoDB\n",
    "    collection.insert_one(price_data)\n",
    "    print(f\"Stored in DB: {price_data}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1a35647a-ca7e-4369-b937-3244a15730d8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
